[
    {
        "snapshot_id": "a9f98c83-2f9e-4b84-906c-026c1ecb014c",
        "name": "GNS3 after ACL",
        "created_at": 1785564898,
        "description": "Snapshot 'GNS3 after ACL' taken on 2026-08-01 at 06:14:58",
        "filename": "GNS3 after ACL.gns3snapshot",
        "project_id": "8cc39bc0-50e8-47c1-9608-6b2aa0d74cff"
    }
]