[
    {
        "snapshot_id": "34889d08-94b6-4f26-ad7d-f1ee8fd27823",
        "name": "GNS3 without ACL",
        "created_at": 1785565138,
        "description": "Snapshot 'GNS3 without ACL' taken on 2026-08-01 at 06:18:58",
        "filename": "GNS3 without ACL.gns3snapshot",
        "project_id": "8cc39bc0-50e8-47c1-9608-6b2aa0d74cff"
    }
]