---
- interface Loopback0
- ip address 10.255.255.2 255.255.255.255
- exit
- interface GigabitEthernet0/1
- description R-EDGE-Link
- ip address 10.255.0.2 255.255.255.252
- no shutdown
- exit
- interface GigabitEthernet0/0
- description SW-CORE-Link
- ip address 10.255.0.5 255.255.255.252
- no shutdown
- exit
- router ospf 1
- router-id 2.2.2.2
- network 10.255.0.0 0.0.0.3 area 0
- network 10.255.0.4 0.0.0.3 area 0
- network 10.255.255.2 0.0.0.0 area 0
- exit
- username admin secret admin@1234
- ip domain-name uor.lk
- ip ssh version 2
- crypto key generate rsa modulus 1024
- service password-encryption
- line vty 0 4
- login local
- exec-timeout 10
- transport input ssh
- exit
- ip access-list standard ACL_MGMT_SSH
- permit 10.99.99.0 0.0.0.255
- deny any
- exit
- line vty 0 4
- access-class ACL_MGMT_SSH in
- exit
- snmp-server community public ro
- snmp-server host 10.99.99.60 version 2c public
